{% set name = "xpdAn" %}
{% set version = "0.8.1" %}
{% set sha256 = "cb63b959f15811a30e8f590c29649425dd81145622efbd3119ef314b6d988ea8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bluesky
    - databroker
    - matplotlib
    - numpy
    - ophyd
    - pyfai
    - pyxdameraulevenshtein
    - pyyaml
    - rapidz
    - scikit-beam
    - scipy
    - shed
    - xpdconf
    - xpdsim
    - xpdtools
    - xpdview
    - xray-vision

test:
  imports:
    - xpdan

about:
  home: https://xpdacq.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python package that aids data analysis at the NSLS-II XPD Beamline.
  dev_url: https://github.com/xpdAcq/xpdAn
  doc_url: https://xpdacq.github.io/xpdAn
