{% set version = "0.8.1" %}

package:
  name: xpdan
  version: {{ version }}

source:
  git_url: https://github.com/xpdAcq/xpdAn.git
  git_rev: {{ version }}
  git_depth: -1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib
    - pyyaml
    - scikit-beam
    - pyfai
    - pyxdameraulevenshtein
    - xray-vision
    - databroker
    - bluesky
    - rapidz
    - xpdsim
    - shed
    - xpdview
    - ophyd
    - xpdtools
    - xpdconf

test:
  imports:
    - xpdan

about:
  home: https://xpdacq.github.io/xpdAn/
  license_file: LICENSE
